const brandData={
  "金御賞集團":{tag:"日式餐飲品牌集團",style:"兼具職人精神、顧客體驗、多品牌經營與日式款待精神",color:[44,30,22],main:"日式餐飲體驗"},
  "金子半之助":{tag:"江戶前天丼專門店",style:"強調江戶前文化、現炸天婦羅、香氣、酥脆口感與親民但有記憶點的日式用餐體驗",color:[111,32,22],main:"江戶前天丼"},
  "辻半":{tag:"海鮮丼飯專門店",style:"強調海味層次、豐盛視覺、儀式感與日式海鮮丼飯體驗",color:[18,55,78],main:"海鮮丼飯"},
  "宇奈鰻魚飯":{tag:"日式鰻魚飯專門店",style:"強調炭火香氣、秘傳醬汁、現烤鰻魚、職人手藝與外酥內嫩的鰻魚飯文化",color:[77,35,24],main:"鰻魚飯"}
};
const hooks={"新品上市":"終於等到了，這次想讓你用一餐記住新的味道。","季節限定":"季節最迷人的地方，就是錯過就要再等一年。","週年慶":"謝謝每一次走進店裡的你，讓我們有機會把一碗飯做到更好。","會員活動":"真正懂吃的熟客，值得被好好款待。","節慶檔期":"把節日過得有儀式感，從一頓好好吃飯開始。","商場導流":"逛街途中，也需要一個讓人願意停下來的理由。","媒體邀約":"一個品牌能被記住，往往從一道有故事的料理開始。","品牌故事":"好的餐飲不只是好吃，而是讓人願意再回來。","顧客回訪":"回訪不是優惠堆出來的，是體驗讓人想再來一次。","新品試吃會":"新品好不好吃，讓第一批懂吃的人先來說。","外帶外送活動":"忙碌的日子，也可以把一份日式好味道帶回家。"};
const ctas={"提升來客數":"現在就安排一餐，把這份限定美味排進你的行程。","提高客單價":"推薦搭配套餐與加點品項，讓這一餐更完整。","新品試吃與曝光":"歡迎來店品嚐，也分享給身邊喜歡日式料理的朋友。","會員回訪":"會員限定內容，記得出示會員資格享受專屬禮遇。","媒體報導":"歡迎媒體朋友與美食創作者預約採訪與拍攝。","社群互動":"留言告訴我們，你最想和誰一起來吃這一餐？"};
const tips={"日式質感":"文字乾淨、有留白，強調料理細節與品牌文化。","親切生活感":"語氣生活化，讓顧客覺得今天就能輕鬆走進來吃。","專業新聞稿":"使用品牌觀點、活動資訊與媒體可引用的正式語氣。","高級感":"強調食材、技法、儀式感與完整用餐體驗。","年輕社群感":"句子短、節奏快，強化畫面感與互動性。","商場促銷感":"主打活動誘因、地點、期間與立即來店理由。"};
function $(id){return document.getElementById(id)}
function v(id){return $(id).value.trim()}
function payload(){return {brand:v('brand'),theme:v('theme'),audience:v('audience'),tone:v('tone'),goal:v('goal'),brief:v('brief')||defaultBrief(),keywords:v('keywords')||defaultKeywords(),period:v('period')||'活動期間依門市公告為準',location:v('location')||'指定門市 / 官方社群公告',offer:v('offer')||ctas[v('goal')],hashtags:v('hashtags')||defaultHashtags(),brandProfile:brandData[v('brand')]}}
function defaultBrief(){const b=brandData[v('brand')];return `${v('brand')}以「${v('theme')}」為主題，結合${b.style}，設計適合${v('audience')}的行銷活動。`}
function defaultKeywords(){const b=brandData[v('brand')];if(v('brand')==='金子半之助')return '江戶前、現炸、天婦羅、天丼、職人精神';if(v('brand')==='辻半')return '海鮮丼、鮮味、儀式感、日式丼飯、豐盛視覺';if(v('brand')==='宇奈鰻魚飯')return '鰻魚飯、炭火香氣、秘傳醬汁、現烤、外酥內嫩';return '金御賞、日式料理、顧客體驗、品牌故事、會員回訪'}
function defaultHashtags(){return `#${v('brand')} #金御賞 #日式料理 #${v('theme')} #餐飲體驗`}
function setStatus(msg){$('status').textContent=msg}
function generateAll(){const p=payload(),b=p.brandProfile;setOutputs({social:makeSocial(p,b),press:makePress(p,b),line:makeLine(p,b),video:makeVideo(p,b),image:makeImagePrompt(p,b),calendar:makeCalendar(p,b)});drawPoster();setStatus('已完成產出。這版不需 API Key，也不會產生任何 API 成本。')}
function setOutputs(o){$('social').textContent=o.social;$('press').textContent=o.press;$('line').textContent=o.line;$('video').textContent=o.video;$('image').textContent=o.image;$('calendar').textContent=o.calendar}
function makeSocial(p,b){return `【Facebook 長文】\n${hooks[p.theme]}\n\n${p.brand}這次以「${p.theme}」為主題，為${p.audience}設計一份更容易靠近、也更有記憶點的餐飲體驗。\n\n活動重點：\n${p.brief}\n\n我們想傳遞的不是單純促銷，而是${b.style}。\n\n活動期間：${p.period}\n活動地點：${p.location}\n活動誘因：${p.offer}\n\n關鍵亮點：${p.keywords}\n\n${ctas[p.goal]}\n\n${p.hashtags}\n\n====================\n\n【Instagram 貼文】\n${hooks[p.theme]}\n\n一份好吃的料理，應該同時有香氣、口感、畫面與故事。\n\n${p.brand}｜${b.tag}\n${p.brief}\n\n推薦給：${p.audience}\n風格：${p.tone}\n重點：${p.keywords}\n\n📍${p.location}\n🗓 ${p.period}\n\n收藏這篇，下次想吃${b.main}時就不會忘記。\n${p.hashtags}\n\n====================\n\n【Threads 短文】\n${hooks[p.theme]}\n\n${p.brand}這次的${p.theme}，不是只想做優惠，而是想讓你多一個「今天就想吃${b.main}」的理由。\n\n${p.offer}\n\n你會想跟誰一起來？`}
function makePress(p,b){return `新聞稿標題：\n${p.brand}推出「${p.theme}」企劃，以${b.tag}打造日式餐飲新體驗\n\n新聞稿前言：\n金御賞旗下品牌${p.brand}宣布推出「${p.theme}」行銷企劃，鎖定${p.audience}，透過${b.style}，強化品牌與消費者之間的連結，並以「${p.goal}」作為本次活動核心目標。\n\n活動內容：\n${p.brief}\n\n活動期間：${p.period}\n活動地點：${p.location}\n活動誘因：${p.offer}\n\n品牌觀點：\n${p.brand}表示，餐飲品牌的競爭不只是產品本身，更包含顧客進店前的期待、用餐中的體驗，以及離店後願不願意再次回訪。本次企劃將以「${p.keywords}」作為溝通主軸，希望讓更多消費者感受到日式料理的細節與溫度。\n\n媒體可拍攝重點：\n1. 主餐特寫與製作過程\n2. 門市空間與顧客用餐情境\n3. 活動限定內容與套餐搭配\n4. 品牌職人精神與日式文化元素\n\n媒體聯絡資訊：\n金御賞公司 行銷部 / 公關窗口`}
function makeLine(p,b){return `【LINE OA 推播】\n${p.brand} ${p.theme}登場！\n${p.brief}\n\n活動期間：${p.period}\n活動地點：${p.location}\n專屬內容：${p.offer}\n\n適合${p.audience}，現在就安排一餐。\n\n====================\n\n【簡訊版】\n${p.brand}${p.theme}活動開跑：${p.offer}。${p.period}，詳情請洽門市或官方社群。\n\n====================\n\n【會員推播標題】\n${p.brand}會員限定｜${p.theme}正式登場\n\n【會員推播短文】\n熟客才懂的好味道，這次準備了${p.offer}。歡迎回來，讓我們用一餐好好款待你。`}
function makeVideo(p,b){return `【15秒短影音腳本】\n0-3秒｜料理特寫 / 製作聲音 / 熱氣與香氣\n字幕：${hooks[p.theme]}\n\n4-8秒｜主餐、套餐、顧客用餐反應\n旁白：${p.brand}這次為${p.audience}準備了新的${p.theme}企劃。\n\n9-12秒｜活動重點快速切換\n字幕：${p.offer}\n\n13-15秒｜品牌 LOGO + 門市 / 訂位資訊\n字幕：${p.period}，現在就來店體驗。\n\n====================\n\n【30秒 Reels 腳本】\n開場鉤子：你有多久沒有好好吃一頓有儀式感的日式料理？\n畫面一：${b.main}近拍，呈現香氣與份量。\n畫面二：職人製作 / 醬汁 / 現炸或現烤畫面。\n畫面三：顧客夾起第一口，搭配表情與環境。\n畫面四：活動資訊與門市位置。\n結尾 CTA：收藏這支影片，下次來${p.location}就知道要吃什麼。`}
function makeImagePrompt(p,b){return `【可貼到 ChatGPT / Canva / Midjourney / Firefly 的圖片提示詞】\n請生成一張適合${p.brand}「${p.theme}」活動的日式餐飲社群主視覺。\n\n品牌：${p.brand}\n品牌定位：${b.tag}\n品牌調性：${b.style}\n主題：${p.theme}\n目標客群：${p.audience}\n語氣風格：${p.tone}\n關鍵字：${p.keywords}\n\n畫面要求：\n1. 日式質感、乾淨留白、暖色燈光。\n2. 料理要看起來真實、美味、有香氣。\n3. 可放置活動標題與門市資訊的留白區。\n4. 適合 Instagram 1:1、Facebook 貼文與 LINE OA 主視覺。\n5. 避免過度卡通、廉價促銷感、雜亂背景、錯誤日文字、過多文字。\n\n建議標題文字：\n${p.brand}｜${p.theme}\n${p.offer}`}
function makeCalendar(p,b){return `【7天行銷排程】\nD-7｜預告貼文：用料理特寫建立期待感。\nD-5｜製程內容：拍攝${b.main}製作細節，強調${p.keywords}。\nD-3｜LINE OA 推播：針對會員與高回訪顧客提醒活動。\nD-1｜倒數貼文：加入門市資訊、活動期間、優惠誘因。\nD-Day｜主視覺貼文 + Reels：社群全面曝光。\nD+3｜顧客回饋：分享評論、照片與熱門品項。\nD+7｜成效回顧：檢視來客數、客單價、會員回訪、社群互動。\n\n【建議追蹤 KPI】\n1. 活動期間營業額\n2. 來客數與客單價\n3. 社群觸及與互動率\n4. LINE OA 點擊率\n5. 會員回訪人數\n6. 媒體 / KOL 曝光數`}
function showTab(e,id){document.querySelectorAll('.panelText').forEach(x=>x.classList.add('hidden'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$(id).classList.remove('hidden');e.target.classList.add('active')}
function allText(){return ['social','press','line','video','image','calendar'].map(id=>$(id).textContent).join('\n\n====================\n\n')}
function copyAll(){navigator.clipboard.writeText(allText());setStatus('已複製全部內容。')}
function downloadText(){const blob=new Blob([allText()],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='金御賞互動式行銷內容.txt';a.click()}
function wrapText(ctx,text,x,y,maxWidth,lineHeight){const chars=String(text).split('');let line='';for(let n=0;n<chars.length;n++){const test=line+chars[n];if(ctx.measureText(test).width>maxWidth&&n>0){ctx.fillText(line,x,y);line=chars[n];y+=lineHeight}else line=test}ctx.fillText(line,x,y);return y}
function drawPoster(){const p=payload(),c=$('poster'),ctx=c.getContext('2d'),b=p.brandProfile;const [r,g,bl]=b.color;ctx.fillStyle=`rgb(${r},${g},${bl})`;ctx.fillRect(0,0,1080,1080);let grd=ctx.createLinearGradient(0,0,1080,1080);grd.addColorStop(0,'rgba(255,230,170,.96)');grd.addColorStop(.34,'rgba(255,255,255,.08)');grd.addColorStop(1,'rgba(0,0,0,.35)');ctx.fillStyle=grd;ctx.fillRect(0,0,1080,1080);ctx.fillStyle='rgba(255,255,255,.12)';for(let i=0;i<9;i++){ctx.beginPath();ctx.arc(90+i*135,160+(i%3)*90,58,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#fff7e8';ctx.font='bold 56px sans-serif';ctx.fillText(p.brand,80,130);ctx.font='900 96px sans-serif';wrapText(ctx,p.theme,80,330,880,110);ctx.font='32px sans-serif';ctx.fillStyle='#ffe7ad';wrapText(ctx,b.tag,80,520,870,44);ctx.fillStyle='rgba(0,0,0,.30)';ctx.fillRect(80,650,920,270);ctx.fillStyle='#fff';ctx.font='40px sans-serif';wrapText(ctx,p.offer,120,735,830,58);ctx.font='bold 34px sans-serif';ctx.fillStyle='#ffe7ad';ctx.fillText(p.period,120,945);ctx.font='26px sans-serif';ctx.fillStyle='rgba(255,255,255,.76)';ctx.fillText(p.location,120,990)}
function downloadPoster(){drawPoster();const a=document.createElement('a');a.href=$('poster').toDataURL('image/png');a.download='金御賞行銷海報草稿.png';a.click()}
function refreshPreview(){drawPoster()}
function generateRandomDemo(){const demos=[{brand:'金子半之助',theme:'季節限定',audience:'上班族午餐客',tone:'日式質感',goal:'提升來客數',brief:'推出季節限定天丼組合，主打現炸天婦羅、江戶前醬汁與午間快速用餐體驗。',keywords:'江戶前、現炸、天婦羅、午餐、季節限定',period:'6/1 - 6/30',location:'台北指定門市',offer:'平日午餐時段套餐升級優惠',hashtags:'#金子半之助 #天丼 #江戶前 #金御賞'},{brand:'辻半',theme:'媒體邀約',audience:'媒體與美食創作者',tone:'專業新聞稿',goal:'媒體報導',brief:'邀請媒體與美食創作者體驗招牌海鮮丼，聚焦豐盛視覺、海味層次與日式丼飯儀式感。',keywords:'海鮮丼、鮮味、儀式感、媒體邀約、美食體驗',period:'即日起開放預約',location:'台北門市',offer:'媒體採訪與創作者體驗預約',hashtags:'#辻半 #海鮮丼 #美食採訪 #金御賞'},{brand:'宇奈鰻魚飯',theme:'新品上市',audience:'美食愛好者',tone:'高級感',goal:'新品試吃與曝光',brief:'推出蒲燒鰻魚飯新品，強調炭火香氣、秘傳醬汁、現烤口感與外酥內嫩的鰻魚飯體驗。',keywords:'鰻魚飯、炭火香氣、秘傳醬汁、現烤、外酥內嫩',period:'6/1 - 6/30',location:'全台指定門市',offer:'新品上市期間會員加購吸物優惠',hashtags:'#宇奈鰻魚飯 #鰻魚飯 #蒲燒鰻魚 #金御賞'}];const d=demos[Math.floor(Math.random()*demos.length)];Object.keys(d).forEach(k=>$(k).value=d[k]);generateAll()}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}});if('serviceWorker'in navigator){navigator.serviceWorker.register('service-worker.js')}
generateAll();
